My_Tech_Blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_app import views as login_views
from blog_app import views as blog_views
from mypage_app import views as mypage_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_views.index,name='index'),
    path('login/',include('login_app.urls')),
    path('logout/',login_views.user_logout,name='logout'),
    path('blog_app/',include('blog_app.urls',namespace='blog_app')),
    path('mypage_app/',include('mypage_app.urls',namespace='mypage_app')),
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blog_app/urls.py
from django.conf.urls import url,include
from django.urls import path
from blog_app import views

app_name = 'blog_app'

urlpatterns = [

    path('',views.PostListView.as_view(),name='list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    path('create/',views.PostCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
    path('post/<int:pk>/comment/', views.CommentCreateView.as_view(), name='add_comment_to_post'),
    path('post/<int:pk>/like/', views.like, name='like'),
]

mypage_app/urls.py
from django.urls import path
from mypage_app import views

# SET THE NAMESPACE!
app_name = 'mypage_app'


urlpatterns=[
        path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
        path('user_update/<int:pk>/', views.UserUpdate, name='user_update'),
        path('user_detail/<int:pk>/follow/', views.follow, name='follow'),

]

mypage_app/models.py
from django.db import models

# Create your models here.

mypage_app/forms.py
from django import forms
from login_app.models import User,UserProfileInfo



class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('username','email','last_name', 'first_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

mypage_app/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.shortcuts import redirect, resolve_url
from django.views import generic
from .forms import UserUpdateForm
# from login_app import models
from django.views.generic import (DetailView,
                                    UpdateView)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model
from login_app.models import UserProfileInfo,Relationship
from django.urls import reverse_lazy


User = get_user_model()
profile = UserProfileInfo

@method_decorator(login_required, name='dispatch')
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

@method_decorator(login_required, name='dispatch')
class UserDetail(DetailView):
    context_object_name = 'user_detail'
    model = User
    template_name = 'mypage_app/user_detail.html'


# @method_decorator(login_required, name='dispatch')
# class UserProfileInfoDetail(DetailView):
#     context_object_name = 'profileInfo_detail'
#     model = UserProfileInfo
#     template_name = 'mypage_app/user_detail.html'
#
#

@login_required
class UserUpdate(OnlyYouMixin,UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'mypage_app/user_form.html'

    def get_success_url(self):
        return resolve_url('mypage_app:user_detail', pk=self.kwargs['pk'])



@login_required
def follow(request, *args, **kwargs):
    followed_user = User.objects.get(id=kwargs['pk'])
    follow_user = request.user
    follow = Relationship.objects.filter(follow=followed_user).filter(follower=follow_user).count()
    if follow_user.follow_num == None:
        follow_user.follow_num == 0
    if followed_user.follower_num == None:
        followed_user.follower_num == 0


    # unfollow
    if follow > 0:
        following = Relationship.objects.get(follow=followed_user, follower=follow_user)
        following.delete()
        follow_user.follow_num -= 1
        followed_user.follower_num -= 1
        follow_user.save()
        followed_user.save()
        return redirect(reverse_lazy('mypage_app:user_detail', kwargs={'pk': kwargs['pk']}))


#follow
    follow_user.follow_num += 1
    followed_user.follower_num += 1
    follow_user.save()
    followed_user.save()
    relationship = Relationship()
    relationship.follower = follow_user
    relationship.follow = followed_user
    relationship.save()
    return redirect(reverse_lazy('mypage_app:user_detail', kwargs={'pk': kwargs['pk']}))

mypage_app/templates/mypage_app/base.html
  {% load static %}
  <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Base</title>
        <link href="{% static 'css/user_detail.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      </head>
      <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
              <li><a class="navbar-brand" href="{% url 'blog_app:list' %}">Posts</a></li>
              <li><a class="navbar-brand" href="{% url 'blog_app:create' %}">Create Posts</a></li>
              <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="navbar-link" href="{% url 'mypage_app:user_detail' user.pk %}">UMy page</a></li>
              <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </nav>
        <div class="container">
          {% block body_block %}
          {% endblock %}
        </div>

      </body>
    </html>

mypage_app/templates/mypage_app/user_detail.html
{% extends "mypage_app/base.html" %}
{% block body_block %}

<div class="cp_tab">
	<input type="radio" name="cp_tab" id="tab1_1" aria-controls="first_tab01" checked>
	<label for="tab1_1">User Infromation</label>
	<input type="radio" name="cp_tab" id="tab1_2" aria-controls="second_tab01">
	<label for="tab1_2">Posts</label>
	<input type="radio" name="cp_tab" id="tab1_3" aria-controls="third_tab01">
	<label for="tab1_3">Comments</label>
	<input type="radio" name="cp_tab" id="tab1_4" aria-controls="fourth_tab01">
	<label for="tab1_4">Liked Posts</label>
	<input type="radio" name="cp_tab" id="tab1_5" aria-controls="fifth_tab01">
	<label for="tab1_5">follow</label>
	<input type="radio" name="cp_tab" id="tab1_6" aria-controls="sixth_tab01">
	<label for="tab1_6">followers</label>


	<div class="cp_tabpanels">
		<div id="first_tab01" class="cp_tabpanel">
      <div class="jumbotron">
        <h2>User Name : {{ user_detail.username }}</h2>
        {% if request.user.pk == user_detail.pk %}
        <h2>Email : {{ user_detail.email }}</h2>
        <h2>Last Name : {{ user_detail.last_name }}</h2>
        <h2>First Name: {{ user_detail.first_name }}<h2>
				<h2>My Introdution</h2>
				<p>{{user_detail.user_profile.introduce }}<p>
        {% endif %}
				{% if user_detail.user_profile.portfolio_site %}
        <h2>Portfolio site : {{user_detail.user_profile.portfolio_site }}</h2>
				{% endif %}
				{% if user_detail.user_profile.profile_pic %}
        <img src="{{ user_detail.user_profile.profile_pic.url }}" alt="Profile Picture" height="300" width="300">
				{% endif %}
      </div>

      {% if request.user.pk == user_detail.pk %}
      <div class="container">
        <p><a class='btn btn-warning' href="{% url 'mypage_app:user_update' pk=request.user.pk %}">Update</a></p>
      </div>
      {% endif %}
			{% if request.user.pk != user_detail.pk %}
			<a class='btn btn-warning' href="{% url 'mypage_app:follow' pk=user_detail.pk %}">follow</a>
			{% endif %}
		</div>

		<div id="second_tab01" class="cp_tabpanel">
			<ol>
			  {% for post in user_detail.posts.all %}
			  <h2><li><a href="{% url 'blog_app:detail' post.id %}">{{post.title}}</a></li></h2>
			  {% endfor %}
			</ol>
		</div>

		<div id="third_tab01" class="cp_tabpanel">
      {% for comment in user_detail.comments.all %}
          <div class="container">
						<h2><li>Post title:<a href="{% url 'blog_app:detail' comment.post.id %}">{{ comment.post.title }}</a></li></h2>
            <h3><strong>{{ comment.author }}</strong></h3>
            <h3><p>{{ comment.text|linebreaks }}</p></h3>
						<h4>{{ comment.created_date }}</h4><hr>
          </div>
      {% empty %}
        <h2>No comments here yet</h2>
      {% endfor %}
		</div>
		<div id="fourth_tab01" class="cp_tabpanel">
      {% for like in user_detail.favorite_posts.all %}
          <div class="container">
						<h2><li>Post title:<a href="{% url 'blog_app:detail' like.post.id %}">{{ like.post.title }}</a></li></h2>
            <h3><strong>{{ like.post.author }}</strong></h3>
            <h3><p>{{ like.post.text|linebreaks }}</p></h3>
						<h4>{{ like.post.created_date }}</h4><hr>
          </div>
      {% empty %}
          <h2>No posts are liked by you</h2>
      {% endfor %}
		</div>
		<div id="fifth_tab01" class="cp_tabpanel">
      {% for follow in user_detail.follows.all %}
          <div class="container">
						<h2><a href="{% url 'mypage_app:user_detail' follow.user.pk %}">{{ follow.username }}</a></h2>
          </div>
      {% empty %}
          <h2>No Follows</h2>
      {% endfor %}
		</div>
		<div id="sixth_tab01" class="cp_tabpanel">
			{% for follower in user_detail.followers.all %}
					<div class="container">
						<h2><a href="{% url 'mypage_app:user_detail' follower.pk %}">{{ follower.username }}</h2>
					</div>
			{% empty %}
					<h2>No Followers</h2>
			{% endfor %}
		</div>

	</div>
</div>



{% endblock %}

mypage_app/templates/mypage_app/user_form.html
{% extends "mypage_app/base.html" %}
{% block body_block %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}