My_Tech_Blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login_app import views as login_views
from blog_app import views as blog_views
from mypage_app import views as mypage_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_views.index,name='index'),
    path('login/',include('login_app.urls')),
    path('logout/',login_views.user_logout,name='logout'),
    path('blog_app/',include('blog_app.urls',namespace='blog_app')),
    path('mypage_app/',include('mypage_app.urls',namespace='mypage_app')),
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blog_app/urls.py
from django.conf.urls import url,include
from django.urls import path
from blog_app import views

app_name = 'blog_app'

urlpatterns = [

    path('',views.PostListView.as_view(),name='list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    path('create/',views.PostCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(),name='delete'),
    path('post/<int:pk>/comment/', views.CommentCreateView.as_view(), name='add_comment_to_post'),
    path('post/<int:pk>/like/', views.like, name='like'),
]

mypage_app/urls.py
from django.urls import path
from mypage_app import views

# SET THE NAMESPACE!
app_name = 'mypage_app'


urlpatterns=[
        path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
        path('user_update/<int:pk>/', views.UserUpdate, name='user_update'),
        path('user_detail/<int:pk>/follow/', views.follow, name='follow'),

]

blog_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField



# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    text = RichTextField()
    author = models.ForeignKey(
        get_user_model(),
        default="",
        on_delete=models.CASCADE,
        related_name='posts'
    )
    tags = TaggableManager()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    live = models.BooleanField(default=False)
    like_num = models.PositiveIntegerField(default=0);

    class Meta:
        ordering = ['-created_date']

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_app:detail',kwargs={'pk':self.pk})


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(
        get_user_model(),
        default="",
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.text



class Like(models.Model):
    user =  models.ForeignKey(
        get_user_model(),
        default="",
        on_delete=models.CASCADE,
        related_name='favorite_posts'
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_posts')
    date_created = models.DateTimeField(auto_now_add=True)

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (View,TemplateView,
                                    ListView,DetailView,
                                    CreateView,UpdateView,DeleteView)
from django.urls import reverse_lazy
from . import models
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.shortcuts import redirect



# Create your views here.
@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post
    # school_list

@method_decorator(login_required, name='dispatch')
class PostDetailView(DetailView):
    context_object_name = 'post_detail'
    model = models.Post
    template_name = 'blog_app/post_detail.html'

@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    fields = ('title','text')
    model = models.Post
    success_url = reverse_lazy("blog_app:list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    fields = ('title','text')
    model = models.Post

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostUpdateView, self).form_valid(form)



@method_decorator(login_required, name='dispatch')
class PostDeleteView(DeleteView):
    model=models.Post
    success_url = reverse_lazy("blog_app:list")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user)


@method_decorator(login_required, name='dispatch')
class CommentCreateView(CreateView):
    fields = ('text',)
    model = models.Comment
    success_url = reverse_lazy("blog_app:detail")

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(models.Post, pk=post_pk)
        form.instance.author = self.request.user

        # 紐づく記事を設定する
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

        # 記事詳細にリダイレクト
        return redirect('blog_app:detail', pk=post_pk)



@login_required
def like(request, *args, **kwargs):
    post = models.Post.objects.get(id=kwargs['pk'])
    is_like = models.Like.objects.filter(user=request.user).filter(post=post).count()
    if post.like_num == None:
        post.like_num == 0

    # unlike
    if is_like > 0:
        liking = models.Like.objects.get(post_id=kwargs['pk'], user=request.user)
        liking.delete()
        post.like_num -= 1
        post.save()
        return redirect(reverse_lazy('blog_app:detail', kwargs={'pk': kwargs['pk']}))
    # like


    post.like_num += 1
    post.save()
    like = models.Like()
    like.user = request.user
    like.post = post
    like.save()
    return redirect(reverse_lazy('blog_app:detail', kwargs={'pk': kwargs['pk']}))

blog_app/templates/blog_app/blog_app_base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load static %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
     {% block extra_head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'blog_app:list' %}">Posts</a></li>
          <li><a class="navbar-brand" href="{% url 'blog_app:create' %}">Create Posts</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'mypage_app:user_detail' pk=request.user.pk %}">User Details</a></li>
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </nav>
    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>

  </body>
</html>

blog_app/templates/blog_app/comment_form.html
{% extends "blog_app/blog_app_base.html" %}

{% block body_block %}

<h1>
  Post Your Comments
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">

</form>
{% endblock %}

blog_app/templates/blog_app/post_confirm_delete.html
{% extends "blog_app/blog_app_base.html" %}

{% block body_block %}
<h1>Delete {{post.title }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'blog_app:detail' pk=post.pk%} ">Cancel</a>

</form>

{% endblock %}

blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/blog_app_base.html" %}


{% block extra_head %}

{% endblock %}

{% block body_block %}


<div class="jumbotron">
  <h1>{{post_detail.title}}</h1>
  <h2>{{ post_detail.text|safe }}</h2>
  <p><a href="{% url 'mypage_app:user_detail' post_detail.author.pk %}">Author: {{post_detail.author}}</a></p>
  <p>Created date: {{post_detail.created_date}}</p>
</div>
{% if request.user == post_detail.author %}
<div class="container">
  <p><a class='btn btn-warning' href="{% url 'blog_app:update' pk=post_detail.pk %}">Update</a></p>
</div>
<div class="container">
  <p><a class='btn btn-warning' href="{% url 'blog_app:delete' pk=post_detail.pk %}">Delete</a></p>
</div>
{% endif %}
{% if request.user != post_detail.author %}
<a class='btn btn-warning' href="{% url 'blog_app:like' pk=post_detail.pk %}">いいね！</a>{{ post_detail.like_num }}
{% endif %}

<a class="btn btn-warning" href="{% url 'blog_app:add_comment_to_post' post_detail.id %}">Add comment</a>

{% for comment in post_detail.comments.all %}
    <div class="container">
        <div class="date">{{ comment.created_date }}</div>
        <h3><strong>{{ comment.author }}</strong></h3>
        {{ comment.text|linebreaks|safe }}
    </div>
{% empty %}
    <h2>No comments here yet</h2>
{% endfor %}

{% endblock %}

blog_app/templates/blog_app/post_form.html
{% extends "blog_app/blog_app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create Post
  {% else %}
  Update Post
  {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">

</form>
{% endblock %}

blog_app/templates/blog_app/post_list.html
{% extends "blog_app/blog_app_base.html"%}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'post_list.css' %}">
{% endblock %}

{%block body_block%}

<h1>Find your favorite blogs</h1>
<ol>
  {% for post in posts %}
  <h2><li><a href="{% url 'blog_app:detail' post.id %}">{{post.title}}</a></li></h2><hr>
  {% endfor %}
</ol>


{%endblock%}

blog_app/templates/blog_app/school_confirm_delete.html
{% extends "blog_app/blog_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'blog_app:detail' pk=school.pk%} ">Cancel</a>

</form>

{% endblock %}

blog_app/templates/blog_app/school_form.html
{% extends "blog_app/blog_app_base.html" %}

{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">

</form>
{% endblock %}